Devnet Update Query
XinFinOrg/XDPoSChain pull request #214
Opened 2022-12-07 03:24 UTC by span14

## Description
This PR creates a new `rpc.BlockNumber` type called `ConfirmedBlockNumber`, which serves to provide users access to the finalized block in V2.

2022-12-07 14:44 UTC, liam-lai commented on eth/api_backend.go
> +			return nil, errors.New("PoW does not support confirmed block loopup")
Lookup

2022-12-07 14:44 UTC, liam-lai commented on eth/api_backend.go
> +		}
Lookup

2022-12-07 21:32 UTC, span14 commented on eth/api_backend.go
> +		}
Fixed

2022-12-07 21:33 UTC, span14 commented on eth/api_backend.go
> +			return nil, errors.New("PoW does not support confirmed block loopup")
Fix

2023-02-02 09:11 UTC, wgr523 approved these changes

2023-02-02 09:28 UTC, wjrjerome requested changes
it looks like the git commit is messed up. Your PR included a lot of my past commits.
Did you rebase or merge dev-upgrade into your branch?
Let's chat in zoom

2023-02-02 09:31 UTC, wgr523 requested changes
rebase needed

2023-02-03 10:37 UTC, wjrjerome approved these changes

2023-02-04 02:43 UTC, merged