eth/hooks: fix panic during sync (#271)
XinFinOrg/XDPoSChain pull request #272
Opened 2023-05-26 03:38 UTC by gzliudan

The issues #268 and #271 reported panic during sync. After debug, I found the panic is caused by https://github.com/XinFinOrg/XDPoSChain/blob/master/eth/hooks/engine_v1_hooks.go#L230-#L231

```go
	adaptor.EngineV1.HookGetSignersFromContract = func(block common.Hash) ([]common.Address, error) {
		client, err := bc.GetClient()
		if err != nil {
			return nil, err
		}
		addr := common.HexToAddress(common.MasternodeVotingSMC)
		validator, err := contractValidator.NewXDCValidator(addr, client)
		if err != nil {
			return nil, err
		}
		opts := new(bind.CallOpts)
		var (
			candidateAddresses []common.Address
			candidates         []utils.Masternode
		)

		stateDB, err := bc.StateAt(bc.GetBlockByHash(block).Root())
		candidateAddresses = state.GetCandidates(stateDB)

		if err != nil {
			return nil, err
		}
```

In our sync test:
- `bc.StateAt(bc.GetBlockByHash(block).Root())` returns nil and err
- then `state.GetCandidates(stateDB)` becomes `state.GetCandidates(nil)`

https://github.com/XinFinOrg/XDPoSChain/blob/master/core/state/statedb_utils.go#L92-#L95

```go
func GetCandidates(statedb *StateDB) []common.Address {
	slot := slotValidatorMapping["candidates"]
	slotHash := common.BigToHash(new(big.Int).SetUint64(slot))
	arrLength := statedb.GetState(common.HexToAddress(common.MasternodeVotingSMC), slotHash)
```

The parameter `statedb` is nil, so `statedb.GetState` cause panic in function `GetCandidates`.

This PR avoid panic bug by check return values `err` and `stateDB` of `bc.StateAt` before call `state.GetCandidates`. The old codes check return value `err` after call `state.GetCandidates`. So this PR fix issue #271. The issue #268 will be fixed by another PR.

2023-05-29 02:22 UTC, liam-lai approved these changes

2023-05-29 02:26 UTC, liam-lai requested changes
I think you just need to move 
```
		candidateAddresses = state.GetCandidates(stateDB)
```
After error handling, don't need to add stateDB == nil

2023-05-29 02:36 UTC, gzliudan commented
Maybe there is such case: `err == nil` and `stateDB == nil`

> I think you just need to move
> 
> ```
> 		candidateAddresses = state.GetCandidates(stateDB)
> ```
> 
> After error handling, don't need to add stateDB == nil

2023-05-29 02:46 UTC, gzliudan commented
I updated codes according to your suggest just now.

2023-05-29 02:49 UTC, liam-lai approved these changes

2023-06-06 06:40 UTC, raghu0891 commented
@gzliudan We are getting the panic issue in our node.

<img width="1086" alt="image" src="https://github.com/XinFinOrg/XDPoSChain/assets/4936467/5551a192-6d59-445b-80e4-5202a0a2c5af">

2024-02-25 04:27 UTC, wjrjerome commented
@gzliudan are we expecting to merge this PR?

2024-02-28 02:36 UTC, closed without merging