PPX-01 add verification of vote signer belonging to masternodes
XinFinOrg/XDPoSChain pull request #498
Opened 2024-03-19 12:43 UTC by wgr523

# Proposed changes
PPX-01 add verification of vote signer belonging to masternodes.

## Types of changes

What types of changes does your code introduce to XDC network?
_Put an `✅` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Regular KTLO or any of the maintaince work. e.g code style
- [ ] CICD Improvement

## Impacted Components
Which part of the codebase this PR will touch base on,

_Put an `✅` in the boxes that apply_

- [x] Consensus
- [ ] Account
- [ ] Network
- [ ] Geth
- [ ] Smart Contract
- [ ] External components
- [ ] Not sure (Please specify below)

## Checklist
_Put an `✅` in the boxes once you have confirmed below actions (or provide reasons on not doing so) that_

- [ ] This PR has sufficient test coverage (unit/integration test) OR I have provided reason in the PR description for not having test coverage
- [ ] Provide an end-to-end test plan in the PR description on how to manually test it on the devnet/testnet.
- [ ] Tested the backwards compatibility.
- [ ] Tested with XDC nodes running this version co-exist with those running the previous version.
- [ ] Relevant documentation has been updated as part of this PR
- [x] N/A

2024-03-20 03:44 UTC, gzliudan commented
Shall we let the function `verifyVotes` return error and check it in the function `voteHandler` ?

2024-03-30 12:50 UTC, liam-lai requested changes
It's better change at `VerifyVoteMessage` function to stop candidate but not masternodes write as signer.

2024-04-01 11:40 UTC, liam-lai approved these changes

2024-04-01 12:48 UTC, wgr523 commented
> Shall we let the function `verifyVotes` return error and check it in the function `voteHandler` ?

the code changed is inside a go routine. the action inside the routine should be clearing the signature. after that, subsequent function can return error if the signature is empty, or not use that vote in a QC.

2024-04-01 12:48 UTC, merged