performance: compare address directly instead of by function String()
XinFinOrg/XDPoSChain pull request #553
Opened 2024-05-29 12:17 UTC by JukLee0ira

# Proposed changes
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.

## Types of changes

What types of changes does your code introduce to XDC network?
_Put an `✅` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Regular KTLO or any of the maintaince work. e.g code style
- [ ] CICD Improvement
- [x] Performance

## Impacted Components
Which part of the codebase this PR will touch base on,

_Put an `✅` in the boxes that apply_

- [ ] Consensus
- [ ] Account
- [ ] Network
- [ ] Geth
- [ ] Smart Contract
- [ ] External components
- [x] Not sure (Please specify below)

## Checklist
_Put an `✅` in the boxes once you have confirmed below actions (or provide reasons on not doing so) that_

- [x] This PR has sufficient test coverage (unit/integration test) OR I have provided reason in the PR description for not having test coverage
- [ ] Provide an end-to-end test plan in the PR description on how to manually test it on the devnet/testnet.
- [ ] Tested the backwards compatibility.
- [ ] Tested with XDC nodes running this version co-exist with those running the previous version.
- [ ] Relevant documentation has been updated as part of this PR
- [ ] N/A

2024-06-02 11:51 UTC, gzliudan commented on XDCx/tradingstate/relayer_state.go
>  		log.Debug("ApplyXDCXMatchedTransaction settle balance: ADD TOKEN XDC NATIVE BEFORE", "token", token.String(), "address", addr.String(), "balance", balance, "orderValue", value)
should replace `token.String()` with `common.XDCNativeAddress`

2024-06-02 11:52 UTC, gzliudan commented on XDCx/tradingstate/relayer_state.go
this empty line should be removed

2024-06-02 11:53 UTC, gzliudan commented on XDCx/tradingstate/relayer_state.go
>  		log.Debug("ApplyXDCXMatchedTransaction settle balance: SUB XDC NATIVE BALANCE BEFORE", "token", token.String(), "address", addr.String(), "balance", balance, "orderValue", value)
don't use `token.String()` here since it is `common.XDCNativeAddres`

2024-06-02 11:54 UTC, gzliudan commented on XDCxlending/lendingstate/relayer.go
>  		log.Debug("ApplyXDCXMatchedTransaction settle balance: SUB XDC NATIVE BALANCE BEFORE", "token", token.String(), "address", addr.String(), "balance", balance, "orderValue", value)
token.String() can be eliminated

2024-06-02 11:56 UTC, gzliudan commented on XDCxlending/order_processor.go
>  		log.Warn("LiquidationExpiredTrade SubTokenBalance", "err", err, "LendingLockAddress", common.HexToAddress(common.LendingLockAddress), "lendingTrade.CollateralLockedAmount", *lendingTrade.Collateral
should use `common.LendingLockAddress` instead of `common.HexToAddress(common.LendingLockAddress)`

2024-06-02 11:57 UTC, gzliudan commented on XDCxlending/order_processor.go
>  		log.Warn("LiquidationTrade SubTokenBalance", "err", err, "LendingLockAddress", common.HexToAddress(common.LendingLockAddress), "lendingTrade.CollateralLockedAmount", *lendingTrade.CollateralLockedA
don't use binary address in log statement

2024-06-02 11:59 UTC, gzliudan commented on XDCxlending/order_processor.go
>  		log.Warn("ProcessTopUpLendingTrade AddTokenBalance", "err", err, "LendingLockAddress", common.HexToAddress(common.LendingLockAddress), "quantity", *quantity, "lendingTrade.CollateralToken", lending
should use constant string variables in log statement

2024-06-02 12:00 UTC, gzliudan commented on XDCxlending/order_processor.go
>  			log.Warn("ProcessRepayLendingTrade SubTokenBalance", "err", err, "LendingLockAddress", common.HexToAddress(common.LendingLockAddress), "lendingTrade.CollateralLockedAmount", *lendingTrade.Collater
don't call common.HexToAddress in log statements

2024-06-02 12:00 UTC, gzliudan commented on XDCxlending/order_processor.go
>  		log.Warn("ProcessRecallLendingTrade SubTokenBalance", "err", err, "LendingLockAddress", common.HexToAddress(common.LendingLockAddress), "recallAmount", *recallAmount, "lendingTrade.CollateralToken"
Need for optimization

2024-06-02 23:44 UTC, gzliudan requested changes
Please also change `skipNonceDestinationAddress = map[string]bool` to `skipNonceDestinationAddress = map[common.Address]bool` or `skipNonceDestinationAddress = map[common.Address]struct{}`. The latter one is better.

2024-06-03 02:01 UTC, gzliudan commented on core/types/transaction.go
>  	return bytes.Equal(toBytes, randomizeSMCBytes) || bytes.Equal(toBytes, blockSignersBytes)
no need call .Bytes()

2024-06-03 04:07 UTC, gzliudan commented on core/types/transaction.go
> +	if _, ok := skipNonceDestinationAddress[*tx.To()]; ok {
can be simplified as below:

```go
_, exist := skipNonceDestinationAddress[*tx.To()]
return exist
```

2024-06-04 00:31 UTC, gzliudan commented on core/types/transaction.go
> +	return to != nil && *to == common.RandomizeSMCBinary || *to == common.BlockSignersBinary
should be:

```go
return to != nil && (*to == common.RandomizeSMCBinary || *to == common.BlockSignersBinary)
```

2024-06-04 00:34 UTC, gzliudan commented on core/types/transaction.go
> +	return to != nil && *to != common.XDCXAddrBinary
should be:

```go
return to != nil && *to == common.XDCXAddrBinary
```

2024-06-04 00:36 UTC, gzliudan commented on core/types/transaction.go
> +	return to != nil && *to != common.XDCXLendingAddressBinary
shoud be:

```go
return to != nil && *to == common.XDCXLendingAddressBinary
```

2024-06-04 00:36 UTC, gzliudan commented on core/types/transaction.go
> +	return to != nil && *to != common.XDCXLendingFinalizedTradeAddressBinary
should be:

```go
return to != nil && *to == common.XDCXLendingFinalizedTradeAddressBinary
```

2024-06-04 00:42 UTC, gzliudan commented on core/types/transaction.go
> +	skipNonceDestinationAddress = map[common.Address]struct{}{
we should use `skipNonceDestinationAddress = map[common.Address]bool` to simplify function `IsSkipNonceTransaction` later.

2024-06-04 00:44 UTC, gzliudan commented on core/types/transaction.go
>  	return false
below code would be better:

```go
to := tx.To()
return to != nil && skipNonceDestinationAddress[*to]
```

2024-06-04 00:46 UTC, gzliudan commented on core/types/transaction.go
> +	if to != nil && *to != common.BlockSignersBinary {
should be:

```go
if to == nil || *to != common.BlockSignersBinary {
```

2024-06-04 01:01 UTC, gzliudan commented on core/types/transaction.go
> +	data := tx.Data()
`data := tx.Data()` can be moved to behind

2024-06-04 01:37 UTC, liam-lai approved these changes

2024-06-04 02:45 UTC, gzliudan commented on core/types/transaction.go
> +	if to == nil && *to != common.BlockSignersBinary {
should be: `if to == nil || *to != common.BlockSignersBinary {`

2024-06-05 03:50 UTC, gzliudan approved these changes

2024-06-11 13:04 UTC, liam-icheng-lai approved these changes
Good Improvement

2024-06-11 13:04 UTC, liam-lai approved these changes
Good improvement

2024-06-11 13:10 UTC, merged