[WIP] Support "input" field in eth_call, eth_estimateGas
XinFinOrg/XDPoSChain pull request #597
Opened 2024-07-31 11:19 UTC by JukLee0ira

# Proposed changes
A user reported a bug in [here](https://www.xdc.dev/steven_lin_1581b1cdfd98a6/wip-ethestimategas-rpc-method-on-apothem-with-erc20-transfer-always-return-execution-reverted-error-5fgl) when using the Go-Ethereum client to call JSON-RPC. The issue arises because the parameter field 'data' has been renamed to 'input' from version 1.13 onwards.

This PR adds support of "input" field in `eth_call`,`eth_estimateGas` . Field "data" will be still supported

## Types of changes

What types of changes does your code introduce to XDC network?
_Put an `✅` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Regular KTLO or any of the maintaince work. e.g code style
- [ ] CICD Improvement
- [x] N/A

## Impacted Components
Which part of the codebase this PR will touch base on,

_Put an `✅` in the boxes that apply_

- [ ] Consensus
- [ ] Account
- [ ] Network
- [x] Geth
- [ ] Smart Contract
- [ ] External components
- [ ] Not sure (Please specify below)

## Checklist
_Put an `✅` in the boxes once you have confirmed below actions (or provide reasons on not doing so) that_

- [ ] This PR has sufficient test coverage (unit/integration test) OR I have provided reason in the PR description for not having test coverage
- [ ] Provide an end-to-end test plan in the PR description on how to manually test it on the devnet/testnet.
- [ ] Tested the backwards compatibility.
- [x] Tested with XDC nodes running this version co-exist with those running the previous version.
- [ ] Relevant documentation has been updated as part of this PR
- [ ] N/A

2024-08-01 12:01 UTC, JukLee0ira commented on internal/ethapi/transaction_args.go
> +	msg := types.NewMessage(addr, args.To, 0, value, gas, gasPrice, data, accessList, false, balanceTokenFee, number)
different with https://github.com/XinFinOrg/XDPoSChain/pull/527/commits/f3e46732c1d6944e30a7bb5cb8dc069d60ff3e9e

2024-08-01 12:02 UTC, JukLee0ira commented on internal/ethapi/transaction_args.go
> +	addr := args.from()
different with https://github.com/XinFinOrg/XDPoSChain/pull/527/commits/f3e46732c1d6944e30a7bb5cb8dc069d60ff3e9e

2024-08-02 03:38 UTC, gzliudan commented
Please use code format for request and json format for response, such as:

<pre>
```shell
// request code
```
 
```json
// response text
```
</pre>

2024-08-02 07:28 UTC, JukLee0ira commented on internal/ethapi/transaction_args.go
> +	msg := types.NewMessage(addr, args.To, 0, value, gas, gasPrice, data, accessList, false, balanceTokenFee, number)
Different parameter counts require implementing EIP-1559

2024-08-02 07:39 UTC, gzliudan requested changes

2024-08-02 07:39 UTC, gzliudan commented on internal/ethapi/api.go
> -	"github.com/XinFinOrg/XDPoSChain/common/sort"
The package `github.com/XinFinOrg/XDPoSChain/common/sort` should be kept in this file. The package `sort` from standard library will cause bug. Please refer to #338.

2024-08-05 06:24 UTC, gzliudan requested changes

2024-08-05 06:24 UTC, gzliudan commented on internal/ethapi/api.go
> -	balanceTokenFee = balanceTokenFee.Mul(balanceTokenFee, gasPrice)
Where is `balanceTokenFee` in your new  codes ?

2024-08-07 01:11 UTC, gzliudan approved these changes
LGTM

2024-08-07 01:46 UTC, wjrjerome approved these changes

2024-08-14 16:32 UTC, gzliudan approved these changes

2024-08-21 06:56 UTC, liam-lai approved these changes

2024-08-21 07:15 UTC, merged